services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_red
    container_name: app_red-container
    ports:
      - "5001:5001"  # Puerto TCP
      - "5000:5000"  # Puerto UDP (si es necesario)
    volumes:
      - /run/NetworkManager:/run/NetworkManager  # Acceso al socket de NetworkManager
      - .:/app  # Monta el directorio actual en /app
      - ./logs:/app/logs  # Para almacenar logs
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /usr/bin/nmcli:/usr/bin/nmcli  # Si quieres que nmcli esté disponible
      - /lib/aarch64-linux-gnu/libnm.so.0:/lib/aarch64-linux-gnu/libnm.so.0:ro  # Biblioteca de nmcli
    privileged: true  # Necesario para acceder a NetworkManager
    user: root  # Ejecutar como root
    network_mode: host  # Necesario para nmcli
